# This is a basic workflow to help you get started with Actions

name: Package Audit

# Controls when the action will run. 
on:
  # schedule:
    # - cron: "*/5 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install deps
        run: npm i

      # Runs a single command using the runners shell
      - name: Create audit file
        run: npm audit --production --json | ./node_modules/.bin/npm-audit-html

      # Runs a set of commands using the runners shell
      - name: Commit the file
        run: |
          git config user.name "Github Action"
          git config user.email github-action@users.noreply.github.com
          git add npm-audit.html
          git commit -m "chore: update packages' audit"
          git push
